# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_example_input": "00_pytorch_to_tflite.ipynb",
         "torch_to_onnx": "00_pytorch_to_tflite.ipynb",
         "onnx_to_tf": "00_pytorch_to_tflite.ipynb",
         "tf_to_tf_lite": "00_pytorch_to_tflite.ipynb",
         "get_torch_model": "00_pytorch_to_tflite.ipynb",
         "get_tf_lite_model": "00_pytorch_to_tflite.ipynb",
         "predict_torch": "00_pytorch_to_tflite.ipynb",
         "predict_tf_lite": "00_pytorch_to_tflite.ipynb",
         "calc_error": "00_pytorch_to_tflite.ipynb",
         "predict_onnx": "00_pytorch_to_tflite.ipynb",
         "onnx_to_keras": "00_pytorch_to_tflite.ipynb"}

modules = ["pytorch_to_tflite.py"]

doc_url = "https://anhvth.github.io/pytorch_to_tflite/"

git_url = "https://github.com/anhvth/pytorch_to_tflite/tree/main/"

def custom_doc_links(name): return None
